import React from 'react'

const contact = () => {
  return (
    <div className='h-[88vh]'>
      This is Contact page 
    </div>
  )
}

export default contact


export const metadata = {
    title: "Contact",
    description: "Generated by create next app",
  };


// page title can be changed when this component is loaded   